### ISSUE TITLE
observation_date

### ISSUE THREAD

**Issue by craigmediaservices** [7astro7/full_fred#1]
Is it possible to alter the observation_date rather than realtime_date?

For example, on series UNRATE I'd like to just grab the last 12 months - but realtime_date wouldn't effect this selection:

```
realtime_start realtime_end        date value
0      2021-05-07   2021-05-07  1948-01-01   3.4
1      2021-05-07   2021-05-07  1948-02-01   3.8
2      2021-05-07   2021-05-07  1948-03-01   4.0
3      2021-05-07   2021-05-07  1948-04-01   3.9
4      2021-05-07   2021-05-07  1948-05-01   3.5
5      2021-05-07   2021-05-07  1948-06-01   3.6
6      2021-05-07   2021-05-07  1948-07-01   3.6
7      2021-05-07   2021-05-07  1948-08-01   3.9
8      2021-05-07   2021-05-07  1948-09-01   3.8
9      2021-05-07   2021-05-07  1948-10-01   3.7
10     2021-05-07   2021-05-07  1948-11-01   3.8
11     2021-05-07   2021-05-07  1948-12-01   4.0
```

Thank you!

**Comment by 7astro7** [comment]
I reproduced your output, will patch and also make observation start and end attributes so repeated passing of them as arguments isn't necessary if they're set

**Comment by 7astro7** [comment]
there's an updated version on pypi and the updated source is available
if the bug persists mention the bug please, will integrate another patch to try to solve it
