### ISSUE TITLE
fred.get_series_df('GOLDPMGBD229NLBM') -> Error cannot create DataFrame

### ISSUE THREAD

**Issue by mabocho** [7astro7/full_fred#4]
**When I run this line of code:**
fred.get_series_df('GOLDPMGBD229NLBM')

**I get the following error message:**
No key 'observations' found, cannot make DataFrame
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-47-59752b4248e6> in <module>
----> 1 df_gold = fred.get_series_df('GOLDPMGBD229NLBM')
      2 df_gold

~\anaconda3\lib\site-packages\full_fred\series.py in get_series_df(self, series_id, realtime_start, realtime_end, limit, offset, sort_order, observation_start, observation_end, units, frequency, aggregation_method, output_type, vintage_dates)
    339             e = "No key 'observations' found, cannot make DataFrame"
    340             print(e)
--> 341         self.series_stack["get_series_df"].pop("observations")
    342         self.series_stack["get_series_df"]["df"] = df
    343         return self.series_stack["get_series_df"]["df"]

KeyError: 'observations'

**Comment by 7astro7** [comment]
I set a breakpoint in the body of the get_series_df method and, using the debugger, the dictionary returned has this: 

```
(Pdb) self.series_stack
{'get_series_df': {'error_code': 404, 'error_message': 'Not Found.  The data for this series is not available via the API;\n                 the data can be found on the FRED website.', 'series_id': 'GOLDPMGBD229NLBM'}}
```

I'll adjust the code to catch situations like this where the data is only available on FRED's website and indicate an updated release here once it's patched and updated on pypi

**Comment by 7astro7** [comment]
New version is up on pypi and source reflects update here on GitHub. If the issue persists with no indication of an error message like the 404 one I got earlier we'll open this issue up again. Thanks for catching this @mabocho
